name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags)
      - name: echo version
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: install nativescript
        run: |
          npm install nativescript@6.5.0
          node_modules/nativescript/bin/tns info
      - name: build for android
        run: |
          node_modules/nativescript/bin/tns build android
      - name: publish to github packages
        env: 
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "https://maven.pkg.github.com/aabeling/you-coach-you/de/banapple/you-coach-you/$VERSION/you-coach-you-$VERSION.apk"
#          curl -X PUT "https://maven.pkg.github.com/aabeling/you-coach-you/de/banapple/you-coach-you/$VERSION/you-coach-you-$VERSION.apk" \
#            -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
#            --upload-file platforms/android/app/build/outputs/apk/debug/app-debug.apk